Update patch set 2
Patch Set 2:

I tried to build this change, and it looks like there's a missing file:

error: bionic/tests/libs/Android.bp:711:1: module "libtest_thread_local_dtor2" variant "linux_glibc_x86_64_static": module source path bionic/tests/libs/thread_local_dtor2.cpp does not exist

Patch-set: 2
Reviewer: Gerrit User 1229339 <1229339@85c56323-6fa9-3386-8a01-6480fb634889>