Update patch set 7
Patch Set 7:

> > > Yeah sync'd and its now generating, but now I am getting:

FYI: It was never generating, when repo detached my branch it put bionic
back onto the Android.mk which was generating the header. The stack trace
dump was because it also put me at the in-tree version of fs_config_generator.py
which attempted to open argv[] as the config.fs ini files (which failed).

 > > >
 > > > FAILED: PATH=$PATH:out/soong/host/linux-x86/bin
 > bionic/libc/fs_config_generator.py
 > > > aidarray system/core/include/private/android_filesystem_config.h
 > > > Traceback (most recent call last):
 > > > File "bionic/libc/fs_config_generator.py", line 279, in
 > <module>
 > > > main()
 > > > File "bionic/libc/fs_config_generator.py", line 273, in main
 > > > parse(x, files, dirs, aids, seen_paths, seen_aids)
 > > > File "bionic/libc/fs_config_generator.py", line 163, in parse
 > > > config.read(file_name)
 > > > File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
 > > > self._read(fp, filename)
 > > > File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
 > > > raise MissingSectionHeaderError(fpname, lineno, line)
 > > > ConfigParser.MissingSectionHeaderError: File contains no
 > section
 > > > headers.
 > > > file: system/core/include/private/android_filesystem_config.h,
 > > > line: 1
 > > > '/*\n'
 > >
 > > WTF repo... took me off my branch and I didn't specify -d on the
 > > sync... tsk one of those days..
 > >
 > > build$ git branch
 > > * (detached from d81beca)
 > > fs-config-2
 > 
 > Nope, I fixed up my tree, and I am still getting:
 > 
 > bionic/libc/bionic/grp_pwd.cpp:47:10: fatal error:
 > 'generated_android_ids.h' file not found
 > #include "generated_android_ids.h"
 > 
 > I don't even see it attempt to generate the header in the build
 > logs, but the command works directly.

Patch-set: 7
Label: Verified=0