Update patch set 2
Patch Set 2: Presubmit-Ready+1

error: system/apex/Android.bp:24:17: unrecognized property "multilib.prefer32"
error: system/apex/Android.bp:22:21: unrecognized property "multilib.lib32.binaries"
error: system/apex/Android.bp:44:13: unrecognized property "filename"

Looks like https://android-review.googlesource.com/c/platform/build/soong/+/800333 isn't merged in the build, which actually was merged yesterday. Weird. 

Retrying.

Patch-set: 2
Reviewer: Gerrit User 1132673 <1132673@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1