Update patch set 3
Patch Set 3:

This breaks builds with SANITIZE_TARGET='address coverage':
error: bionic/libm/Android.bp:6:1: module "libm" variant "android_arm64_armv8-a_static": Use of "coverage" also requires "address"

Patch-set: 3