Update patch set 2
Patch Set 2:

This change breaks aosp_llvm build with following errors:

error: bionic/tests/Android.bp:399:1: module "bionic-unit-tests" variant "android_arm_armv7-a": depends on disabled module "libBionicLoaderTests"
error: bionic/tests/Android.bp:399:1: module "bionic-unit-tests" variant "android_arm_armv7-a": depends on disabled module "libLLVMObject"

Not sure why. Considering that first dependency is not something new.

Patch-set: 2
Label: Presubmit-Ready=0