Update patch set 1
Patch Set 1: Code-Review+1

I tried to build x86 emulator with clang and, after your patch is applied, I got the following error:
 
target  C: libc_gdtoa <= bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c
bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c:228:11: error: incomplete definition of type 'struct ieee_ext'
        *sign = p->ext_sign;
                ~^

it seems some upstream-* files have other issues as well (some may be caused by particular gcc feature not supported by clang)
As for x86/x86_64 assemblies subset your patch is fixing suffixes correctly in these particular cases and you are right there are more…
 
Generally, we don't have any preferences about the compiler choice for building bionic at this point. It would be interesting though to see the implications of the potential compiler change (do you have any insights?).
In any case we can fix suffixes in the rest of the x86[_64] functions in the near future.

Patch-set: 1
Reviewer: Gerrit User 1017368 <1017368@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=+1