Move some basic __*_t definitions into separate header
Define this chunk in separate header like glibc does in bits/types.h. In
-ffreestanding mode GCC replacing stdint.h with it's own copy which
defines own [u]intX_t types but doesn't have __[u]intX_t defined and
that leads to:

sys/types.h:45:1: error: unknown type name '__uint32_t'

Change-Id: I826b36873862d1d70b47401f31f4369a77666b8e
Signed-off-by: Pavel Chupin <pavel.v.chupin@intel.com>