Update patch set 1
Patch Set 1:

(2 comments)

_GNU_SOURCE enables the GNU version of basename, but if libgen.h is included, then the libgen.h/POSIX version takes precedence.

It occurred to me after I uploaded this patch that the linker already prevents the inclusion of libgen.h:

    bionic/libc/include/libgen.h:68:7: error: functions that differ only in their return type cannot be overloaded

The linker includes headers from various other places in Android, though (e.g. libbase, libziparchive), so those headers must also not include libgen.h. I'm not sure the linker should be enforcing that?

For some more motivation: we have places in the linker that are correct, but they're fragile, e.g.:

    const char* bname = basename(dt_needed);
    if (bname != dt_needed) {
    ...
    return bname;

The bname is eventually assigned to "const char* LoadTask::name_". This looks dangerous, but it works as long as libgen.h isn't included. If it were included, I'm not sure our unit tests would catch it, because this code only runs for targetSdk < 23. (I think it would be too broken to get past app-compat testing.)

    if (name[0] == '/' && dirname(name) == kSystemLibDir) {

This looks wrong, because kSystemLibDir is a string literal, and I normally expect dirname to return char*.

libgen.h's basename/dirname functions return nullptr if the result is too large. They touch __bionic_tls, which isn't available until after __libc_init_main_thread_late runs. I *think* that's OK, but I'd prefer not to think about it.

Patch-set: 1