Record correct previous dispatch hooks.
If there was another heapprofd signal racing, it could happen that we
ran HandleHeapprofdSignal with the ephermal hooks installed, which made
it remember `nullptr` as the previous hooks. Repro in
https://android-review.googlesource.com/c/platform/bionic/+/1767868

(lldb) c
Process 1736 resuming
Process 1736 stopped
* thread #16, name = 'android.display', stop reason = breakpoint 1.1
    frame #0: 0x00000077af494d78 libc.so`HeapprofdMallopt(int, void*, unsigned long) [inlined] DispatchReset(this=<unavailable>)::$_4::operator()() const::'lambda'(libc_globals*)::operator()(libc_globals*) const at malloc_heapprofd.cpp:441:51
   438
   439 	    if(atomic_compare_exchange_strong(&gHeapprofdState, &expected, kUninstallingHook)){
   440 	      __libc_globals.mutate([](libc_globals* globals) {
-> 441 	        const MallocDispatch* previous_dispatch = atomic_load(&gPreviousDefaultDispatchTable);
   442 	        atomic_store(&globals->default_dispatch_table, previous_dispatch);
   443 	        if (!MallocLimitInstalled()) {
   444 	          atomic_store(&globals->current_dispatch_table, previous_dispatch);
(lldb) p gPreviousDefaultDispatchTable
error: need to add support for DW_TAG_base_type 'auto' encoded with DW_ATE = 0x0, bit_size = 0
warning: `this' is not accessible (substituting 0)
(_Atomic(const MallocDispatch *)) $0 = 0x0000000000000000


Bug: 193012939
Bug: 189776979
Change-Id: I6d89ee0b8a899766a1b939f9666791fd20a6e0db