Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2:
> > > 
> > > > Patch Set 2:
> > > > 
> > > > I think "make SANITIZE_TARGET=hwaddress oatdump" should do it.
> > > 
> > > http://ag/6016502
> > > http://ag/6016503
> > > 
> > > uploaded as a quick fix.
> > 
> > These changes won't fix hwasan, right?
> 
> yes, right. doesn't fix the hwasan build. could you point me the build breakage? (branch/target)

git_master_throttled, walleye_hwasan - but for some reason it has not built anything since this morning.

The error looks like this:
prebuilts/clang/host/linux-x86/clang-r346389c/lib64/clang/8.0.7/lib/linux/libclang_rt.hwasan-aarch64-android.so: error: undefined reference to 'strlen', version 'LIBC'

Patch-set: 2
Reviewer: Gerrit User 1005967 <1005967@85c56323-6fa9-3386-8a01-6480fb634889>