Update patch set 4
Patch Set 4:

(1 comment)

> Patch Set 4:
> 
> > Patch Set 3:
> > 
> > (3 comments)
> > 
> > See http://b/111611546 for discussion on argv editing in the zygote.
> > 
> > If I understand correctly, the kernel provides a contiguous block of memory containing the arguments, separated by NULs. This CL shifts down the argv[...] pointers in the KernelArgumentBlock. I wondered if it also ought to shift down the contents. If it did, then /proc/.../cmdline wouldn't show the linker, and I think ps/top/pidof would use the invoked executable name rather than `linker64`.
> > 
> > OTOH, I think the cmdline would end with trailing NULs. To fix that, the linker would need to call prctl(PR_SET_MM, PR_SET_MM_ARG_END, new_end_address, 0, 0), which requires CAP_SYS_RESOURCES.
> 
> /proc/self/exe will still point to the linker/linker64 if I understand this correctly. I do not think the linker is supposed to fix up everything so it looks like as if the executable was loaded directly by the kernel.

Yeah, it seems reasonable to leave the /proc/self/... alone. I wonder if we should still remove the initial "linker[64]" argument or touch up AT_xxx values. I went into more detail on enh's comment.

> btw, is this going to work for static executables? e.g. /system/bin/linker a_static_executable

It doesn't work for either static or non-PIE executables. The error message is a little bare-bones:

    error: "/data/local/tmp/a.out" has unexpected e_type: 2

ET_EXEC is 2, and ET_DYN is 3. A PIE executable has an e_type of ET_DYN, and the linker only expects to load shared objects.

Patch-set: 4
Reviewer: Gerrit User 1229339 <1229339@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0