Update patch set 2
Patch Set 2:

This broke the build, which bionicbb had correctly identified...

bionic/libc/bionic/semaphore.cpp:44:10: fatal error: 'private/bionic_sdk_version.h' file not found
#include "private/bionic_sdk_version.h"
         ^
1 error generated.

Patch-set: 2
Reviewer: Gerrit User 1043845 <1043845@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0