tests Android.mk: add -Wno-sign-compare c flag
when compile the cts package with aarch64 gcc4.9,
will get following error:

bionic/tests/wchar_test.cpp:253:3:   required from here
external/gtest/include/gtest/gtest.h:1448:16:
     error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

by adding -Wno-sign-compare to the cflag, we can get this error pass

Change-Id: Icc2a69f5e2fa46b563df1cd3079c2b95048ad031
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>