libc: Implement lockf() and lockf64() - DO NOT SUBMIT
Do not submit yet, because for some weird reason, the
lockf_test.cpp file doesn't build. The compiler complains
at lines like:

  ASSERT_TRUE(fp != NULL);

or

  ASSERT_NE(fp, NULL);

With:

  bionic/tests/lockf_test.cpp:32:317: error: void value not ignored as it ought to be
  ...
  external/gtest/include/gtest/gtest.h: In function 'testing::AssertionResult testing::internal::CmpHelperNE(char const*, char const*, const T1&, const T2&) [with T1 = __sFILE*, T2 = int]':
  bionic/tests/lockf_test.cpp:32:139:   instantiated from here
external/gtest/include/gtest/gtest.h:1445:136: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]

(is it a gtest bug?)

Change-Id: I8399a9acffa247a39dea814bbd96f42a59fd27f4