Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Is there another CL along with this?
> 
> I couldn't get it to build on TOT, I see this error:
> 
> In file included from bionic/linker/linker_tls.cpp:40:
> In file included from bionic/linker/linker_main.h:36:
> In file included from bionic/linker/linker_namespaces.h:31:
> In file included from bionic/linker/linker_common_types.h:32:
> In file included from bionic/linker/linked_list.h:31:
> system/core/base/include/android-base/macros.h:83:9: error: 'LIKELY' macro redefined [-Werror,-Wmacro-redefined]
> #define LIKELY( exp )       (__builtin_expect( (exp) != 0, true  ))
>         ^
> external/gwp_asan/gwp_asan/definitions.h:17:9: note: previous definition is here
> #define LIKELY(X) __builtin_expect(!!(X), 1)
> 
> Is there an update to external/gwp_asan? Is something including one definition incorrectly?
> 
> I also see the same error for the UNLIKELY macro.

Yes, there are a couple of things that I have local patches for. I'll try and get at least the provisional patchset out so that you can build successfully - but there's some changes (like the ones above) that need to go upstream to LLVM.

Patch-set: 3