Update patch set 2
Patch Set 2:

here's the complaint:

  frameworks/native/libs/vr/libbufferhubqueue/buffer_hub_queue_client.cpp:52:34: error: constant expression evaluates to -2147483647 which cannot be narrowed to type 'uint32_t' (aka 'unsigned int') [-Wc++11-narrowing]
    epoll_event event = {.events = EPOLLIN | EPOLLET,
                                   ^~~~~~~~~~~~~~~~~
  bionic/libc/include/sys/epoll.h:43:26: note: expanded from macro 'EPOLLIN'
  #define EPOLLIN          0x00000001
                           ^

the weird part being that EPOLLIN didn't change. but EPOLLET changed to (1<<31) instead of 0xblah. but i don't understand why that should make any difference from clang's point of view? aren't both ways of writing it implicitly signed?

Patch-set: 2
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0