HACK for linux_bionic builds
I'm not sure why this is required, but liblog/logger_write.c fails to
compile with:

bionic/libc/kernel/uapi/linux/uio.h:25:8: error: field has incomplete type 'void'

Test: none
Change-Id: I62dec72450b67af8fbb6cf08f9d3b4ec6c42b221