Disable missing-field-initializers warning for bionic
```
bionic/libc/stdio/stdio.cpp:84:21: error: missing field '_ub' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:88:21: error: missing field '_ub' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:92:21: error: missing field '_ub' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:98:5: error: missing field '_size' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:98:5: error: missing field '_p' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:99:5: error: missing field '_size' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:99:5: error: missing field '_p' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:100:5: error: missing field '_size' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/stdio/stdio.cpp:100:5: error: missing field '_p' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/private/ScopedSignalHandler.h:25:61: error: missing field 'sa_mask' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/private/ScopedSignalHandler.h:32:62: error: missing field 'sa_mask' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/fdsan.cpp:66:46: error: missing field 'rlim_cur' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/fdsan.cpp:66:46: error: missing field 'rlim_cur' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/sleep.cpp:39:50: error: missing field 'tv_nsec' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/spawn.cpp:145:65: error: missing field 'sa_flags' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/signal.cpp:161:51: error: missing field 'sa_flags' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/signal.cpp:196:70: error: missing field 'sa_mask' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/signal.cpp:240:55: error: missing field 'sa_flags' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/net_if.cpp:51:56: error: missing field 'ifr_ifrn' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/abort.cpp:49:75: error: missing field 'sa_mask' initializer [-Werror,-Wmissing-field-initializers]
bionic/libc/bionic/malloc_common_dynamic.cpp:301:5: error: missing field 'reserved_addr' initializer [-Werror,-Wmissing-field-initializers]
```

Bug: b/312573090

Change-Id: I74898e76f0599588d71853259feb5c5d073b249d