include definition of in_addr_t in arpa/inet.h
Building the Linux kernel's CONFIG_UAPI_HEADER_TEST against a prebuilt
bionic sysroot from the NDK fails with the error:

  HDRTEST usr/include/linux/fsi.h
In file included from <built-in>:1:
In file included from ./usr/include/linux/tipc_config.h:46:
prebuilts/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/arpa/inet.h:39:1:
error: unknown type name 'in_addr_t'
in_addr_t inet_addr(const char* __s);
^

This is because the kernel's generated usr/include/tipc_config.h
includes <arpa/inet.h>.

Bionic's include/arpa/inet.h uses in_addr_t without including the
definition of the type from bits/in_addr.h.

Bug: 190019968
Test: LTO=none BUILD_CONFIG=common/build.config.gki.aarch64 ./build/build.sh
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Icb0045a9087c2e892cae7503519b0b80769a845d