Update patch set 4
Patch Set 4:

even with the other two changes in, i still can't build this:

bionic/tests/stdatomic_test.cpp:71: error: undefined reference to '__atomic_is_lock_free'

Patch-set: 4
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0