Update patch set 7
Patch Set 7:

the build fails when bionic is compiled with clang, the error message is like below:
bionic/libc/bionic/getcwd.cpp:36:7: error: redefinition of a 'extern inline' function 'getcwd' is not supported in C++
char* getcwd(char* buf, size_t size) {
      ^
bionic/libc/include/unistd.h:259:7: note: previous definition is here
char* getcwd(char* buf, size_t size) {
      ^
1 error generated.
make: *** [out/target/product/mako/obj/STATIC_LIBRARIES/libc_bionic_ndk_intermediates/bionic/getcwd.o] Error 1

I think we need to add #undef _FORTIFY_SOURCE in getcwd.cpp.
@Daniel, could you upload a new separate change for it?

Patch-set: 7