Update patch set 3
Patch Set 3:

change it to warning doesn't fix the problem, because gcc still tries to link it. The error message is as below:
out/target/product/flounder/obj/SHARED_LIBRARIES/libcamera_client_intermediates/CameraParameters.o: In function `write':
/ssd2/android/aosp_test/bionic/libc/include/unistd.h:452: undefined reference to `__write_count_toobig_error'
out/target/product/flounder/obj/SHARED_LIBRARIES/libcamera_client_intermediates/CameraParameters2.o: In function `write':
/ssd2/android/aosp_test/bionic/libc/include/unistd.h:452: undefined reference to `__write_count_toobig_error'
collect2: error: ld returned 1 exit status

The only solution seems to remove the __write_count_toobig_error() check. However, I think we are taking advantage of some optimization that is not very stable on gcc. As it doesn't hurt anyone without this change, I suggest we wait and see if things can become better in gcc or clang.

Patch-set: 3
Label: Verified=0