Update patch set 1
Patch Set 1:

Hi Dimitry, 

I know you have a concern on the '# vndk' tag (there even is a bug: http://b/38100184), but I think this is unavoidable.

Without this CL, a vendor lib built with a sanitizer can't be built with following error. (since llndk stub of libdl does not have the symbol)

/tmp/lto-llvm-666e43.o:ld-temp.o:function android::AAtomizer::AAtomizer(): error: undefined reference to '__cfi_slowpath_diag'
/tmp/lto-llvm-666e43.o:ld-temp.o:function android::AAtomizer::AAtomizer(): error: undefined reference to '__cfi_slowpath_diag'
/tmp/lto-llvm-666e43.o:ld-temp.o:function android::AAtomizer::atomize(char const*): error: undefined reference to '__cfi_slowpath_diag'
/tmp/lto-llvm-666e43.o:ld-temp.o:function android::AAtomizer::atomize(char const*): error: undefined reference to '__cfi_slowpath_diag'

Patch-set: 1
Reviewer: Gerrit User 1041673 <1041673@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1074628 <1074628@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1010186 <1010186@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1120458 <1120458@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1132673 <1132673@85c56323-6fa9-3386-8a01-6480fb634889>