Update patch set 2
Patch Set 2:

While fixing this, I also try to pull the full vfprintf.c from upstream.
I don't know your current progress with it, may be you already passed the point that I reached.
Still may be helpful:

vfprintf depends on gdtoa thing, so I had to pull that as well.
Also it depends on nl_langinfo, so I had to pull libc/upstream-openbsd/lib/libc/locale/nl_langinfo.c
which lead to pulling libc/upstream-openbsd/lib/libc/locale/rune* that depends on libc/upstream-openbsd/lib/libc/citrus/* that I also have taken.
Also I had to add _MUTEX_LOCK/_MUTEX_UNLOCK/_MUTEX_DESTROY to libc/private/thread_private.h.

The problem that I encountered lastly was:

bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c:133: error: undefined reference to '__fpclassifyd'
bionic/libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c:230: error: undefined reference to '__fpclassifyl'
bionic/libc/upstream-openbsd/lib/libc/gdtoa/ldtoa.c:80: error: undefined reference to '__fpclassifyl'

which is strange, because gdtoa is a part of libc and it shouldn't depend on libm.. 

This is only for x86_64, I didn't touch anything else.
If you think it could be helpful, I can upload the whole patch.

Anyway, thanks for committing the fix.

Here is the full list of changed/pulled files:


M       libc/Android.mk
M       libc/arch-x86_64/x86_64.mk
A       libc/include/langinfo.h
A       libc/include/nl_types.h
M       libc/private/thread_private.h
M       libc/stdio/floatio.h
A       libc/upstream-openbsd/lib/libc/arch/amd64/gdtoa/Makefile.inc
A       libc/upstream-openbsd/lib/libc/arch/amd64/gdtoa/arith.h
A       libc/upstream-openbsd/lib/libc/arch/amd64/gdtoa/gd_qnan.h
A       libc/upstream-openbsd/lib/libc/arch/amd64/gdtoa/strtold.c
A       libc/upstream-openbsd/lib/libc/citrus/citrus_ctype.c
A       libc/upstream-openbsd/lib/libc/citrus/citrus_ctype.h
A       libc/upstream-openbsd/lib/libc/citrus/citrus_ctype_local.h
A       libc/upstream-openbsd/lib/libc/citrus/citrus_none.c
A       libc/upstream-openbsd/lib/libc/citrus/citrus_none.h
A       libc/upstream-openbsd/lib/libc/citrus/citrus_utf8.c
A       libc/upstream-openbsd/lib/libc/citrus/citrus_utf8.h
A       libc/upstream-openbsd/lib/libc/gdtoa/Makefile.inc
A       libc/upstream-openbsd/lib/libc/gdtoa/arith.h
A       libc/upstream-openbsd/lib/libc/gdtoa/dmisc.c
A       libc/upstream-openbsd/lib/libc/gdtoa/dtoa.c
A       libc/upstream-openbsd/lib/libc/gdtoa/gd_qnan.h
A       libc/upstream-openbsd/lib/libc/gdtoa/gdtoa.c
A       libc/upstream-openbsd/lib/libc/gdtoa/gdtoa.h
A       libc/upstream-openbsd/lib/libc/gdtoa/gdtoa_fltrnds.h
A       libc/upstream-openbsd/lib/libc/gdtoa/gdtoaimp.h
A       libc/upstream-openbsd/lib/libc/gdtoa/gethex.c
A       libc/upstream-openbsd/lib/libc/gdtoa/gmisc.c
A       libc/upstream-openbsd/lib/libc/gdtoa/hd_init.c
A       libc/upstream-openbsd/lib/libc/gdtoa/hdtoa.c
A       libc/upstream-openbsd/lib/libc/gdtoa/hexnan.c
A       libc/upstream-openbsd/lib/libc/gdtoa/ldtoa.c
A       libc/upstream-openbsd/lib/libc/gdtoa/locks.c
A       libc/upstream-openbsd/lib/libc/gdtoa/misc.c
A       libc/upstream-openbsd/lib/libc/gdtoa/smisc.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtod.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtodg.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtof.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtold.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtorQ.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtord.c
A       libc/upstream-openbsd/lib/libc/gdtoa/strtorx.c
A       libc/upstream-openbsd/lib/libc/gdtoa/sum.c
A       libc/upstream-openbsd/lib/libc/gdtoa/ulp.c
A       libc/upstream-openbsd/lib/libc/locale/nl_langinfo.c
A       libc/upstream-openbsd/lib/libc/locale/rune.h
A       libc/upstream-openbsd/lib/libc/locale/rune_local.h
A       libc/upstream-openbsd/lib/libc/locale/runetable.c
A       libc/upstream-openbsd/lib/libc/locale/runetype.h
A       libc/upstream-openbsd/lib/libc/stdio/vfprintf.c

Patch-set: 2
Reviewer: Gerrit User 1017368 <1017368@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0